/*
Samsara API

Integrate your data with the Samsara API, customize the Samsara experience, and join a community of developers building with Samsara.

API version: 2019-12-12
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the VehicleStatsEngineState type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VehicleStatsEngineState{}

// VehicleStatsEngineState Vehicle engine state event.
type VehicleStatsEngineState struct {
	// UTC timestamp in RFC 3339 format. Example: `2020-01-27T07:06:25Z`.
	Time time.Time `json:"time"`
	// The state of the engine.
	Value string `json:"value"`
}

type _VehicleStatsEngineState VehicleStatsEngineState

// NewVehicleStatsEngineState instantiates a new VehicleStatsEngineState object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVehicleStatsEngineState(time time.Time, value string) *VehicleStatsEngineState {
	this := VehicleStatsEngineState{}
	this.Time = time
	this.Value = value
	return &this
}

// NewVehicleStatsEngineStateWithDefaults instantiates a new VehicleStatsEngineState object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVehicleStatsEngineStateWithDefaults() *VehicleStatsEngineState {
	this := VehicleStatsEngineState{}
	return &this
}

// GetTime returns the Time field value
func (o *VehicleStatsEngineState) GetTime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Time
}

// GetTimeOk returns a tuple with the Time field value
// and a boolean to check if the value has been set.
func (o *VehicleStatsEngineState) GetTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Time, true
}

// SetTime sets field value
func (o *VehicleStatsEngineState) SetTime(v time.Time) {
	o.Time = v
}

// GetValue returns the Value field value
func (o *VehicleStatsEngineState) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *VehicleStatsEngineState) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *VehicleStatsEngineState) SetValue(v string) {
	o.Value = v
}

func (o VehicleStatsEngineState) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VehicleStatsEngineState) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["time"] = o.Time
	toSerialize["value"] = o.Value
	return toSerialize, nil
}

func (o *VehicleStatsEngineState) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"time",
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVehicleStatsEngineState := _VehicleStatsEngineState{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVehicleStatsEngineState)

	if err != nil {
		return err
	}

	*o = VehicleStatsEngineState(varVehicleStatsEngineState)

	return err
}

type NullableVehicleStatsEngineState struct {
	value *VehicleStatsEngineState
	isSet bool
}

func (v NullableVehicleStatsEngineState) Get() *VehicleStatsEngineState {
	return v.value
}

func (v *NullableVehicleStatsEngineState) Set(val *VehicleStatsEngineState) {
	v.value = val
	v.isSet = true
}

func (v NullableVehicleStatsEngineState) IsSet() bool {
	return v.isSet
}

func (v *NullableVehicleStatsEngineState) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVehicleStatsEngineState(val *VehicleStatsEngineState) *NullableVehicleStatsEngineState {
	return &NullableVehicleStatsEngineState{value: val, isSet: true}
}

func (v NullableVehicleStatsEngineState) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVehicleStatsEngineState) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


