/*
Samsara API

Integrate your data with the Samsara API, customize the Samsara experience, and join a community of developers building with Samsara.

API version: 2019-12-12
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package samsarago

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ListAddressesResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListAddressesResponse{}

// ListAddressesResponse A list of Addresses and pagination information.
type ListAddressesResponse struct {
	// A list of Addresses.
	Data []Address `json:"data"`
	Pagination PaginationResponse `json:"pagination"`
}

type _ListAddressesResponse ListAddressesResponse

// NewListAddressesResponse instantiates a new ListAddressesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListAddressesResponse(data []Address, pagination PaginationResponse) *ListAddressesResponse {
	this := ListAddressesResponse{}
	this.Data = data
	this.Pagination = pagination
	return &this
}

// NewListAddressesResponseWithDefaults instantiates a new ListAddressesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListAddressesResponseWithDefaults() *ListAddressesResponse {
	this := ListAddressesResponse{}
	return &this
}

// GetData returns the Data field value
func (o *ListAddressesResponse) GetData() []Address {
	if o == nil {
		var ret []Address
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ListAddressesResponse) GetDataOk() ([]Address, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *ListAddressesResponse) SetData(v []Address) {
	o.Data = v
}

// GetPagination returns the Pagination field value
func (o *ListAddressesResponse) GetPagination() PaginationResponse {
	if o == nil {
		var ret PaginationResponse
		return ret
	}

	return o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value
// and a boolean to check if the value has been set.
func (o *ListAddressesResponse) GetPaginationOk() (*PaginationResponse, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pagination, true
}

// SetPagination sets field value
func (o *ListAddressesResponse) SetPagination(v PaginationResponse) {
	o.Pagination = v
}

func (o ListAddressesResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListAddressesResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["pagination"] = o.Pagination
	return toSerialize, nil
}

func (o *ListAddressesResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"pagination",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListAddressesResponse := _ListAddressesResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListAddressesResponse)

	if err != nil {
		return err
	}

	*o = ListAddressesResponse(varListAddressesResponse)

	return err
}

type NullableListAddressesResponse struct {
	value *ListAddressesResponse
	isSet bool
}

func (v NullableListAddressesResponse) Get() *ListAddressesResponse {
	return v.value
}

func (v *NullableListAddressesResponse) Set(val *ListAddressesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListAddressesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListAddressesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListAddressesResponse(val *ListAddressesResponse) *NullableListAddressesResponse {
	return &NullableListAddressesResponse{value: val, isSet: true}
}

func (v NullableListAddressesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListAddressesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


