/*
Samsara API

Integrate your data with the Samsara API, customize the Samsara experience, and join a community of developers building with Samsara.

API version: 2019-12-12
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package samsarago

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateTagRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateTagRequest{}

// CreateTagRequest struct for CreateTagRequest
type CreateTagRequest struct {
	// The addresses that belong to this tag.
	Addresses []string `json:"addresses,omitempty"`
	// The trailers, unpowered, and powered assets that belong to this tag.
	Assets []string `json:"assets,omitempty"`
	// The drivers that belong to this tag.
	Drivers []string `json:"drivers,omitempty"`
	// The machines that belong to this tag.
	Machines []string `json:"machines,omitempty"`
	// Name of this tag.
	Name string `json:"name"`
	// If this tag is part a hierarchical tag tree, this is the ID of the parent tag, otherwise this will be omitted.
	ParentTagId *string `json:"parentTagId,omitempty"`
	// The sensors that belong to this tag.
	Sensors []string `json:"sensors,omitempty"`
	// The vehicles that belong to this tag.
	Vehicles []string `json:"vehicles,omitempty"`
}

type _CreateTagRequest CreateTagRequest

// NewCreateTagRequest instantiates a new CreateTagRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateTagRequest(name string) *CreateTagRequest {
	this := CreateTagRequest{}
	this.Name = name
	return &this
}

// NewCreateTagRequestWithDefaults instantiates a new CreateTagRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateTagRequestWithDefaults() *CreateTagRequest {
	this := CreateTagRequest{}
	return &this
}

// GetAddresses returns the Addresses field value if set, zero value otherwise.
func (o *CreateTagRequest) GetAddresses() []string {
	if o == nil || IsNil(o.Addresses) {
		var ret []string
		return ret
	}
	return o.Addresses
}

// GetAddressesOk returns a tuple with the Addresses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTagRequest) GetAddressesOk() ([]string, bool) {
	if o == nil || IsNil(o.Addresses) {
		return nil, false
	}
	return o.Addresses, true
}

// HasAddresses returns a boolean if a field has been set.
func (o *CreateTagRequest) HasAddresses() bool {
	if o != nil && !IsNil(o.Addresses) {
		return true
	}

	return false
}

// SetAddresses gets a reference to the given []string and assigns it to the Addresses field.
func (o *CreateTagRequest) SetAddresses(v []string) {
	o.Addresses = v
}

// GetAssets returns the Assets field value if set, zero value otherwise.
func (o *CreateTagRequest) GetAssets() []string {
	if o == nil || IsNil(o.Assets) {
		var ret []string
		return ret
	}
	return o.Assets
}

// GetAssetsOk returns a tuple with the Assets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTagRequest) GetAssetsOk() ([]string, bool) {
	if o == nil || IsNil(o.Assets) {
		return nil, false
	}
	return o.Assets, true
}

// HasAssets returns a boolean if a field has been set.
func (o *CreateTagRequest) HasAssets() bool {
	if o != nil && !IsNil(o.Assets) {
		return true
	}

	return false
}

// SetAssets gets a reference to the given []string and assigns it to the Assets field.
func (o *CreateTagRequest) SetAssets(v []string) {
	o.Assets = v
}

// GetDrivers returns the Drivers field value if set, zero value otherwise.
func (o *CreateTagRequest) GetDrivers() []string {
	if o == nil || IsNil(o.Drivers) {
		var ret []string
		return ret
	}
	return o.Drivers
}

// GetDriversOk returns a tuple with the Drivers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTagRequest) GetDriversOk() ([]string, bool) {
	if o == nil || IsNil(o.Drivers) {
		return nil, false
	}
	return o.Drivers, true
}

// HasDrivers returns a boolean if a field has been set.
func (o *CreateTagRequest) HasDrivers() bool {
	if o != nil && !IsNil(o.Drivers) {
		return true
	}

	return false
}

// SetDrivers gets a reference to the given []string and assigns it to the Drivers field.
func (o *CreateTagRequest) SetDrivers(v []string) {
	o.Drivers = v
}

// GetMachines returns the Machines field value if set, zero value otherwise.
func (o *CreateTagRequest) GetMachines() []string {
	if o == nil || IsNil(o.Machines) {
		var ret []string
		return ret
	}
	return o.Machines
}

// GetMachinesOk returns a tuple with the Machines field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTagRequest) GetMachinesOk() ([]string, bool) {
	if o == nil || IsNil(o.Machines) {
		return nil, false
	}
	return o.Machines, true
}

// HasMachines returns a boolean if a field has been set.
func (o *CreateTagRequest) HasMachines() bool {
	if o != nil && !IsNil(o.Machines) {
		return true
	}

	return false
}

// SetMachines gets a reference to the given []string and assigns it to the Machines field.
func (o *CreateTagRequest) SetMachines(v []string) {
	o.Machines = v
}

// GetName returns the Name field value
func (o *CreateTagRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateTagRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateTagRequest) SetName(v string) {
	o.Name = v
}

// GetParentTagId returns the ParentTagId field value if set, zero value otherwise.
func (o *CreateTagRequest) GetParentTagId() string {
	if o == nil || IsNil(o.ParentTagId) {
		var ret string
		return ret
	}
	return *o.ParentTagId
}

// GetParentTagIdOk returns a tuple with the ParentTagId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTagRequest) GetParentTagIdOk() (*string, bool) {
	if o == nil || IsNil(o.ParentTagId) {
		return nil, false
	}
	return o.ParentTagId, true
}

// HasParentTagId returns a boolean if a field has been set.
func (o *CreateTagRequest) HasParentTagId() bool {
	if o != nil && !IsNil(o.ParentTagId) {
		return true
	}

	return false
}

// SetParentTagId gets a reference to the given string and assigns it to the ParentTagId field.
func (o *CreateTagRequest) SetParentTagId(v string) {
	o.ParentTagId = &v
}

// GetSensors returns the Sensors field value if set, zero value otherwise.
func (o *CreateTagRequest) GetSensors() []string {
	if o == nil || IsNil(o.Sensors) {
		var ret []string
		return ret
	}
	return o.Sensors
}

// GetSensorsOk returns a tuple with the Sensors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTagRequest) GetSensorsOk() ([]string, bool) {
	if o == nil || IsNil(o.Sensors) {
		return nil, false
	}
	return o.Sensors, true
}

// HasSensors returns a boolean if a field has been set.
func (o *CreateTagRequest) HasSensors() bool {
	if o != nil && !IsNil(o.Sensors) {
		return true
	}

	return false
}

// SetSensors gets a reference to the given []string and assigns it to the Sensors field.
func (o *CreateTagRequest) SetSensors(v []string) {
	o.Sensors = v
}

// GetVehicles returns the Vehicles field value if set, zero value otherwise.
func (o *CreateTagRequest) GetVehicles() []string {
	if o == nil || IsNil(o.Vehicles) {
		var ret []string
		return ret
	}
	return o.Vehicles
}

// GetVehiclesOk returns a tuple with the Vehicles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTagRequest) GetVehiclesOk() ([]string, bool) {
	if o == nil || IsNil(o.Vehicles) {
		return nil, false
	}
	return o.Vehicles, true
}

// HasVehicles returns a boolean if a field has been set.
func (o *CreateTagRequest) HasVehicles() bool {
	if o != nil && !IsNil(o.Vehicles) {
		return true
	}

	return false
}

// SetVehicles gets a reference to the given []string and assigns it to the Vehicles field.
func (o *CreateTagRequest) SetVehicles(v []string) {
	o.Vehicles = v
}

func (o CreateTagRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateTagRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Addresses) {
		toSerialize["addresses"] = o.Addresses
	}
	if !IsNil(o.Assets) {
		toSerialize["assets"] = o.Assets
	}
	if !IsNil(o.Drivers) {
		toSerialize["drivers"] = o.Drivers
	}
	if !IsNil(o.Machines) {
		toSerialize["machines"] = o.Machines
	}
	toSerialize["name"] = o.Name
	if !IsNil(o.ParentTagId) {
		toSerialize["parentTagId"] = o.ParentTagId
	}
	if !IsNil(o.Sensors) {
		toSerialize["sensors"] = o.Sensors
	}
	if !IsNil(o.Vehicles) {
		toSerialize["vehicles"] = o.Vehicles
	}
	return toSerialize, nil
}

func (o *CreateTagRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateTagRequest := _CreateTagRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateTagRequest)

	if err != nil {
		return err
	}

	*o = CreateTagRequest(varCreateTagRequest)

	return err
}

type NullableCreateTagRequest struct {
	value *CreateTagRequest
	isSet bool
}

func (v NullableCreateTagRequest) Get() *CreateTagRequest {
	return v.value
}

func (v *NullableCreateTagRequest) Set(val *CreateTagRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateTagRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateTagRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateTagRequest(val *CreateTagRequest) *NullableCreateTagRequest {
	return &NullableCreateTagRequest{value: val, isSet: true}
}

func (v NullableCreateTagRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateTagRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


