/*
Samsara API

Integrate your data with the Samsara API, customize the Samsara experience, and join a community of developers building with Samsara.

API version: 2019-12-12
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package samsarago

import (
	"encoding/json"
)

// checks if the Tag type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Tag{}

// Tag struct for Tag
type Tag struct {
	// Unique Samsara ID of this tag.
	Id *string `json:"id,omitempty"`
	// Name of this tag.
	Name *string `json:"name,omitempty"`
	// If this tag is part a hierarchical tag tree, this is the ID of the parent tag, otherwise this will be omitted.
	ParentTagId *string `json:"parentTagId,omitempty"`
	// The addresses that belong to this tag.
	Addresses []TaggedObject `json:"addresses,omitempty"`
	// The trailers, unpowered, and powered assets that belong to this tag.
	Assets []TaggedObject `json:"assets,omitempty"`
	// The drivers that belong to this tag.
	Drivers []TaggedObject `json:"drivers,omitempty"`
	// The machines that belong to thistag.
	Machines []TaggedObject `json:"machines,omitempty"`
	ParentTag *ParentTag `json:"parentTag,omitempty"`
	// The sensors that belong to this tag.
	Sensors []TaggedObject `json:"sensors,omitempty"`
	// The vehicles that belong to this tag.
	Vehicles []TaggedObject `json:"vehicles,omitempty"`
}

// NewTag instantiates a new Tag object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTag() *Tag {
	this := Tag{}
	return &this
}

// NewTagWithDefaults instantiates a new Tag object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTagWithDefaults() *Tag {
	this := Tag{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Tag) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Tag) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Tag) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Tag) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *Tag) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Tag) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *Tag) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *Tag) SetName(v string) {
	o.Name = &v
}

// GetParentTagId returns the ParentTagId field value if set, zero value otherwise.
func (o *Tag) GetParentTagId() string {
	if o == nil || IsNil(o.ParentTagId) {
		var ret string
		return ret
	}
	return *o.ParentTagId
}

// GetParentTagIdOk returns a tuple with the ParentTagId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Tag) GetParentTagIdOk() (*string, bool) {
	if o == nil || IsNil(o.ParentTagId) {
		return nil, false
	}
	return o.ParentTagId, true
}

// HasParentTagId returns a boolean if a field has been set.
func (o *Tag) HasParentTagId() bool {
	if o != nil && !IsNil(o.ParentTagId) {
		return true
	}

	return false
}

// SetParentTagId gets a reference to the given string and assigns it to the ParentTagId field.
func (o *Tag) SetParentTagId(v string) {
	o.ParentTagId = &v
}

// GetAddresses returns the Addresses field value if set, zero value otherwise.
func (o *Tag) GetAddresses() []TaggedObject {
	if o == nil || IsNil(o.Addresses) {
		var ret []TaggedObject
		return ret
	}
	return o.Addresses
}

// GetAddressesOk returns a tuple with the Addresses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Tag) GetAddressesOk() ([]TaggedObject, bool) {
	if o == nil || IsNil(o.Addresses) {
		return nil, false
	}
	return o.Addresses, true
}

// HasAddresses returns a boolean if a field has been set.
func (o *Tag) HasAddresses() bool {
	if o != nil && !IsNil(o.Addresses) {
		return true
	}

	return false
}

// SetAddresses gets a reference to the given []TaggedObject and assigns it to the Addresses field.
func (o *Tag) SetAddresses(v []TaggedObject) {
	o.Addresses = v
}

// GetAssets returns the Assets field value if set, zero value otherwise.
func (o *Tag) GetAssets() []TaggedObject {
	if o == nil || IsNil(o.Assets) {
		var ret []TaggedObject
		return ret
	}
	return o.Assets
}

// GetAssetsOk returns a tuple with the Assets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Tag) GetAssetsOk() ([]TaggedObject, bool) {
	if o == nil || IsNil(o.Assets) {
		return nil, false
	}
	return o.Assets, true
}

// HasAssets returns a boolean if a field has been set.
func (o *Tag) HasAssets() bool {
	if o != nil && !IsNil(o.Assets) {
		return true
	}

	return false
}

// SetAssets gets a reference to the given []TaggedObject and assigns it to the Assets field.
func (o *Tag) SetAssets(v []TaggedObject) {
	o.Assets = v
}

// GetDrivers returns the Drivers field value if set, zero value otherwise.
func (o *Tag) GetDrivers() []TaggedObject {
	if o == nil || IsNil(o.Drivers) {
		var ret []TaggedObject
		return ret
	}
	return o.Drivers
}

// GetDriversOk returns a tuple with the Drivers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Tag) GetDriversOk() ([]TaggedObject, bool) {
	if o == nil || IsNil(o.Drivers) {
		return nil, false
	}
	return o.Drivers, true
}

// HasDrivers returns a boolean if a field has been set.
func (o *Tag) HasDrivers() bool {
	if o != nil && !IsNil(o.Drivers) {
		return true
	}

	return false
}

// SetDrivers gets a reference to the given []TaggedObject and assigns it to the Drivers field.
func (o *Tag) SetDrivers(v []TaggedObject) {
	o.Drivers = v
}

// GetMachines returns the Machines field value if set, zero value otherwise.
func (o *Tag) GetMachines() []TaggedObject {
	if o == nil || IsNil(o.Machines) {
		var ret []TaggedObject
		return ret
	}
	return o.Machines
}

// GetMachinesOk returns a tuple with the Machines field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Tag) GetMachinesOk() ([]TaggedObject, bool) {
	if o == nil || IsNil(o.Machines) {
		return nil, false
	}
	return o.Machines, true
}

// HasMachines returns a boolean if a field has been set.
func (o *Tag) HasMachines() bool {
	if o != nil && !IsNil(o.Machines) {
		return true
	}

	return false
}

// SetMachines gets a reference to the given []TaggedObject and assigns it to the Machines field.
func (o *Tag) SetMachines(v []TaggedObject) {
	o.Machines = v
}

// GetParentTag returns the ParentTag field value if set, zero value otherwise.
func (o *Tag) GetParentTag() ParentTag {
	if o == nil || IsNil(o.ParentTag) {
		var ret ParentTag
		return ret
	}
	return *o.ParentTag
}

// GetParentTagOk returns a tuple with the ParentTag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Tag) GetParentTagOk() (*ParentTag, bool) {
	if o == nil || IsNil(o.ParentTag) {
		return nil, false
	}
	return o.ParentTag, true
}

// HasParentTag returns a boolean if a field has been set.
func (o *Tag) HasParentTag() bool {
	if o != nil && !IsNil(o.ParentTag) {
		return true
	}

	return false
}

// SetParentTag gets a reference to the given ParentTag and assigns it to the ParentTag field.
func (o *Tag) SetParentTag(v ParentTag) {
	o.ParentTag = &v
}

// GetSensors returns the Sensors field value if set, zero value otherwise.
func (o *Tag) GetSensors() []TaggedObject {
	if o == nil || IsNil(o.Sensors) {
		var ret []TaggedObject
		return ret
	}
	return o.Sensors
}

// GetSensorsOk returns a tuple with the Sensors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Tag) GetSensorsOk() ([]TaggedObject, bool) {
	if o == nil || IsNil(o.Sensors) {
		return nil, false
	}
	return o.Sensors, true
}

// HasSensors returns a boolean if a field has been set.
func (o *Tag) HasSensors() bool {
	if o != nil && !IsNil(o.Sensors) {
		return true
	}

	return false
}

// SetSensors gets a reference to the given []TaggedObject and assigns it to the Sensors field.
func (o *Tag) SetSensors(v []TaggedObject) {
	o.Sensors = v
}

// GetVehicles returns the Vehicles field value if set, zero value otherwise.
func (o *Tag) GetVehicles() []TaggedObject {
	if o == nil || IsNil(o.Vehicles) {
		var ret []TaggedObject
		return ret
	}
	return o.Vehicles
}

// GetVehiclesOk returns a tuple with the Vehicles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Tag) GetVehiclesOk() ([]TaggedObject, bool) {
	if o == nil || IsNil(o.Vehicles) {
		return nil, false
	}
	return o.Vehicles, true
}

// HasVehicles returns a boolean if a field has been set.
func (o *Tag) HasVehicles() bool {
	if o != nil && !IsNil(o.Vehicles) {
		return true
	}

	return false
}

// SetVehicles gets a reference to the given []TaggedObject and assigns it to the Vehicles field.
func (o *Tag) SetVehicles(v []TaggedObject) {
	o.Vehicles = v
}

func (o Tag) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Tag) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.ParentTagId) {
		toSerialize["parentTagId"] = o.ParentTagId
	}
	if !IsNil(o.Addresses) {
		toSerialize["addresses"] = o.Addresses
	}
	if !IsNil(o.Assets) {
		toSerialize["assets"] = o.Assets
	}
	if !IsNil(o.Drivers) {
		toSerialize["drivers"] = o.Drivers
	}
	if !IsNil(o.Machines) {
		toSerialize["machines"] = o.Machines
	}
	if !IsNil(o.ParentTag) {
		toSerialize["parentTag"] = o.ParentTag
	}
	if !IsNil(o.Sensors) {
		toSerialize["sensors"] = o.Sensors
	}
	if !IsNil(o.Vehicles) {
		toSerialize["vehicles"] = o.Vehicles
	}
	return toSerialize, nil
}

type NullableTag struct {
	value *Tag
	isSet bool
}

func (v NullableTag) Get() *Tag {
	return v.value
}

func (v *NullableTag) Set(val *Tag) {
	v.value = val
	v.isSet = true
}

func (v NullableTag) IsSet() bool {
	return v.isSet
}

func (v *NullableTag) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTag(val *Tag) *NullableTag {
	return &NullableTag{value: val, isSet: true}
}

func (v NullableTag) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTag) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


