/*
Samsara API

Integrate your data with the Samsara API, customize the Samsara experience, and join a community of developers building with Samsara.

API version: 2019-12-12
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the UserRoleAssignmentTag type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserRoleAssignmentTag{}

// UserRoleAssignmentTag The tag that this role is applies to.
type UserRoleAssignmentTag struct {
	// ID of the tag.
	Id *string `json:"id,omitempty"`
	// Name of the tag.
	Name *string `json:"name,omitempty"`
}

// NewUserRoleAssignmentTag instantiates a new UserRoleAssignmentTag object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserRoleAssignmentTag() *UserRoleAssignmentTag {
	this := UserRoleAssignmentTag{}
	return &this
}

// NewUserRoleAssignmentTagWithDefaults instantiates a new UserRoleAssignmentTag object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserRoleAssignmentTagWithDefaults() *UserRoleAssignmentTag {
	this := UserRoleAssignmentTag{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *UserRoleAssignmentTag) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserRoleAssignmentTag) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *UserRoleAssignmentTag) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *UserRoleAssignmentTag) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *UserRoleAssignmentTag) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserRoleAssignmentTag) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *UserRoleAssignmentTag) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *UserRoleAssignmentTag) SetName(v string) {
	o.Name = &v
}

func (o UserRoleAssignmentTag) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserRoleAssignmentTag) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableUserRoleAssignmentTag struct {
	value *UserRoleAssignmentTag
	isSet bool
}

func (v NullableUserRoleAssignmentTag) Get() *UserRoleAssignmentTag {
	return v.value
}

func (v *NullableUserRoleAssignmentTag) Set(val *UserRoleAssignmentTag) {
	v.value = val
	v.isSet = true
}

func (v NullableUserRoleAssignmentTag) IsSet() bool {
	return v.isSet
}

func (v *NullableUserRoleAssignmentTag) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserRoleAssignmentTag(val *UserRoleAssignmentTag) *NullableUserRoleAssignmentTag {
	return &NullableUserRoleAssignmentTag{value: val, isSet: true}
}

func (v NullableUserRoleAssignmentTag) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserRoleAssignmentTag) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


