/*
Samsara API

Integrate your data with the Samsara API, customize the Samsara experience, and join a community of developers building with Samsara.

API version: 2019-12-12
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package samsarago

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the VehicleStatsGpsDistanceMeters type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VehicleStatsGpsDistanceMeters{}

// VehicleStatsGpsDistanceMeters Vehicle GPS distance event.
type VehicleStatsGpsDistanceMeters struct {
	// UTC timestamp in RFC 3339 format. Example: `2020-01-27T07:06:25Z`.
	Time time.Time `json:"time"`
	// Number of meters the vehicle has traveled since the gateway was installed, based on GPS calculations.
	Value float64 `json:"value"`
}

type _VehicleStatsGpsDistanceMeters VehicleStatsGpsDistanceMeters

// NewVehicleStatsGpsDistanceMeters instantiates a new VehicleStatsGpsDistanceMeters object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVehicleStatsGpsDistanceMeters(time time.Time, value float64) *VehicleStatsGpsDistanceMeters {
	this := VehicleStatsGpsDistanceMeters{}
	this.Time = time
	this.Value = value
	return &this
}

// NewVehicleStatsGpsDistanceMetersWithDefaults instantiates a new VehicleStatsGpsDistanceMeters object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVehicleStatsGpsDistanceMetersWithDefaults() *VehicleStatsGpsDistanceMeters {
	this := VehicleStatsGpsDistanceMeters{}
	return &this
}

// GetTime returns the Time field value
func (o *VehicleStatsGpsDistanceMeters) GetTime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Time
}

// GetTimeOk returns a tuple with the Time field value
// and a boolean to check if the value has been set.
func (o *VehicleStatsGpsDistanceMeters) GetTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Time, true
}

// SetTime sets field value
func (o *VehicleStatsGpsDistanceMeters) SetTime(v time.Time) {
	o.Time = v
}

// GetValue returns the Value field value
func (o *VehicleStatsGpsDistanceMeters) GetValue() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *VehicleStatsGpsDistanceMeters) GetValueOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *VehicleStatsGpsDistanceMeters) SetValue(v float64) {
	o.Value = v
}

func (o VehicleStatsGpsDistanceMeters) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VehicleStatsGpsDistanceMeters) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["time"] = o.Time
	toSerialize["value"] = o.Value
	return toSerialize, nil
}

func (o *VehicleStatsGpsDistanceMeters) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"time",
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVehicleStatsGpsDistanceMeters := _VehicleStatsGpsDistanceMeters{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVehicleStatsGpsDistanceMeters)

	if err != nil {
		return err
	}

	*o = VehicleStatsGpsDistanceMeters(varVehicleStatsGpsDistanceMeters)

	return err
}

type NullableVehicleStatsGpsDistanceMeters struct {
	value *VehicleStatsGpsDistanceMeters
	isSet bool
}

func (v NullableVehicleStatsGpsDistanceMeters) Get() *VehicleStatsGpsDistanceMeters {
	return v.value
}

func (v *NullableVehicleStatsGpsDistanceMeters) Set(val *VehicleStatsGpsDistanceMeters) {
	v.value = val
	v.isSet = true
}

func (v NullableVehicleStatsGpsDistanceMeters) IsSet() bool {
	return v.isSet
}

func (v *NullableVehicleStatsGpsDistanceMeters) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVehicleStatsGpsDistanceMeters(val *VehicleStatsGpsDistanceMeters) *NullableVehicleStatsGpsDistanceMeters {
	return &NullableVehicleStatsGpsDistanceMeters{value: val, isSet: true}
}

func (v NullableVehicleStatsGpsDistanceMeters) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVehicleStatsGpsDistanceMeters) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


