/*
Samsara API

Integrate your data with the Samsara API, customize the Samsara experience, and join a community of developers building with Samsara.

API version: 2019-12-12
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package samsarago

import (
	"encoding/json"
)

// checks if the TagResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TagResponse{}

// TagResponse A single tag.
type TagResponse struct {
	Data *Tag `json:"data,omitempty"`
}

// NewTagResponse instantiates a new TagResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTagResponse() *TagResponse {
	this := TagResponse{}
	return &this
}

// NewTagResponseWithDefaults instantiates a new TagResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTagResponseWithDefaults() *TagResponse {
	this := TagResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *TagResponse) GetData() Tag {
	if o == nil || IsNil(o.Data) {
		var ret Tag
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TagResponse) GetDataOk() (*Tag, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *TagResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given Tag and assigns it to the Data field.
func (o *TagResponse) SetData(v Tag) {
	o.Data = &v
}

func (o TagResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TagResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableTagResponse struct {
	value *TagResponse
	isSet bool
}

func (v NullableTagResponse) Get() *TagResponse {
	return v.value
}

func (v *NullableTagResponse) Set(val *TagResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTagResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTagResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTagResponse(val *TagResponse) *NullableTagResponse {
	return &NullableTagResponse{value: val, isSet: true}
}

func (v NullableTagResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTagResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


