/*
Samsara API

Integrate your data with the Samsara API, customize the Samsara experience, and join a community of developers building with Samsara.

API version: 2019-12-12
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package samsarago

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VehicleLocationsListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VehicleLocationsListResponse{}

// VehicleLocationsListResponse List of vehicle location events and pagination info.
type VehicleLocationsListResponse struct {
	// A list of vehicles and an array of location events for each vehicle.
	Data []VehicleLocationsListResponseDataInner `json:"data"`
	Pagination PaginationResponse `json:"pagination"`
}

type _VehicleLocationsListResponse VehicleLocationsListResponse

// NewVehicleLocationsListResponse instantiates a new VehicleLocationsListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVehicleLocationsListResponse(data []VehicleLocationsListResponseDataInner, pagination PaginationResponse) *VehicleLocationsListResponse {
	this := VehicleLocationsListResponse{}
	this.Data = data
	this.Pagination = pagination
	return &this
}

// NewVehicleLocationsListResponseWithDefaults instantiates a new VehicleLocationsListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVehicleLocationsListResponseWithDefaults() *VehicleLocationsListResponse {
	this := VehicleLocationsListResponse{}
	return &this
}

// GetData returns the Data field value
func (o *VehicleLocationsListResponse) GetData() []VehicleLocationsListResponseDataInner {
	if o == nil {
		var ret []VehicleLocationsListResponseDataInner
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *VehicleLocationsListResponse) GetDataOk() ([]VehicleLocationsListResponseDataInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *VehicleLocationsListResponse) SetData(v []VehicleLocationsListResponseDataInner) {
	o.Data = v
}

// GetPagination returns the Pagination field value
func (o *VehicleLocationsListResponse) GetPagination() PaginationResponse {
	if o == nil {
		var ret PaginationResponse
		return ret
	}

	return o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value
// and a boolean to check if the value has been set.
func (o *VehicleLocationsListResponse) GetPaginationOk() (*PaginationResponse, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pagination, true
}

// SetPagination sets field value
func (o *VehicleLocationsListResponse) SetPagination(v PaginationResponse) {
	o.Pagination = v
}

func (o VehicleLocationsListResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VehicleLocationsListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["pagination"] = o.Pagination
	return toSerialize, nil
}

func (o *VehicleLocationsListResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"pagination",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVehicleLocationsListResponse := _VehicleLocationsListResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVehicleLocationsListResponse)

	if err != nil {
		return err
	}

	*o = VehicleLocationsListResponse(varVehicleLocationsListResponse)

	return err
}

type NullableVehicleLocationsListResponse struct {
	value *VehicleLocationsListResponse
	isSet bool
}

func (v NullableVehicleLocationsListResponse) Get() *VehicleLocationsListResponse {
	return v.value
}

func (v *NullableVehicleLocationsListResponse) Set(val *VehicleLocationsListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableVehicleLocationsListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableVehicleLocationsListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVehicleLocationsListResponse(val *VehicleLocationsListResponse) *NullableVehicleLocationsListResponse {
	return &NullableVehicleLocationsListResponse{value: val, isSet: true}
}

func (v NullableVehicleLocationsListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVehicleLocationsListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


