/*
Samsara API

Integrate your data with the Samsara API, customize the Samsara experience, and join a community of developers building with Samsara.

API version: 2019-12-12
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package samsarago

import (
	"encoding/json"
)

// checks if the ListContactsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListContactsResponse{}

// ListContactsResponse A list of contacts.
type ListContactsResponse struct {
	Data []Contact `json:"data,omitempty"`
	Pagination *PaginationResponse `json:"pagination,omitempty"`
}

// NewListContactsResponse instantiates a new ListContactsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListContactsResponse() *ListContactsResponse {
	this := ListContactsResponse{}
	return &this
}

// NewListContactsResponseWithDefaults instantiates a new ListContactsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListContactsResponseWithDefaults() *ListContactsResponse {
	this := ListContactsResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ListContactsResponse) GetData() []Contact {
	if o == nil || IsNil(o.Data) {
		var ret []Contact
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListContactsResponse) GetDataOk() ([]Contact, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ListContactsResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []Contact and assigns it to the Data field.
func (o *ListContactsResponse) SetData(v []Contact) {
	o.Data = v
}

// GetPagination returns the Pagination field value if set, zero value otherwise.
func (o *ListContactsResponse) GetPagination() PaginationResponse {
	if o == nil || IsNil(o.Pagination) {
		var ret PaginationResponse
		return ret
	}
	return *o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListContactsResponse) GetPaginationOk() (*PaginationResponse, bool) {
	if o == nil || IsNil(o.Pagination) {
		return nil, false
	}
	return o.Pagination, true
}

// HasPagination returns a boolean if a field has been set.
func (o *ListContactsResponse) HasPagination() bool {
	if o != nil && !IsNil(o.Pagination) {
		return true
	}

	return false
}

// SetPagination gets a reference to the given PaginationResponse and assigns it to the Pagination field.
func (o *ListContactsResponse) SetPagination(v PaginationResponse) {
	o.Pagination = &v
}

func (o ListContactsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListContactsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Pagination) {
		toSerialize["pagination"] = o.Pagination
	}
	return toSerialize, nil
}

type NullableListContactsResponse struct {
	value *ListContactsResponse
	isSet bool
}

func (v NullableListContactsResponse) Get() *ListContactsResponse {
	return v.value
}

func (v *NullableListContactsResponse) Set(val *ListContactsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListContactsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListContactsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListContactsResponse(val *ListContactsResponse) *NullableListContactsResponse {
	return &NullableListContactsResponse{value: val, isSet: true}
}

func (v NullableListContactsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListContactsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


